CREATE DATABASE DATABASE_DOGFRIENDS;

USE DATABASE_DOGFRIENDS;

CREATE TABLE TB_PROPRIETARIO(
  CPF			 VARCHAR(11) PRIMARY KEY,
  EMAIL			 VARCHAR(100) UNIQUE NOT NULL,
  SENHA			 VARCHAR(30) NOT NULL,
  NOME		     VARCHAR(100) NOT NULL,
  TELEFONE		 VARCHAR(20) NOT NULL,
  SEXO			 VARCHAR(10),
  DT_NASCIMENTO  DATE,
  FOTO			 TEXT,
  DESCRICAO		 TEXT
);

CREATE TABLE TB_ANIMAL(
  ID	         INTEGER PRIMARY KEY AUTO_INCREMENT,
  NOME			 VARCHAR(50) NOT NULL,
  SEXO		     VARCHAR(10) NOT NULL,
  DT_NASCIMENTO  DATE,
  FOTO			 TEXT,
  TIPO_ANIMAL    VARCHAR(10) NOT NULL,
  RACA		     VARCHAR(30),
  PORTE			 VARCHAR(15),
  FAZ_ATIVIDADE	 VARCHAR(10),
  COMPORTAMENTO  TEXT,
  CPF_PROP	     VARCHAR(11) NOT NULL,
  
  CONSTRAINT FK_CPF_PROP_ANIMAL FOREIGN KEY (CPF_PROP) REFERENCES TB_PROPRIETARIO (CPF)
);

CREATE TABLE TB_DOGWALKER(
  CPF			 VARCHAR(11) PRIMARY KEY,
  EMAIL			 VARCHAR(100) UNIQUE NOT NULL,
  SENHA			 VARCHAR(30) NOT NULL,
  NOME		     VARCHAR(100) NOT NULL,
  TELEFONE		 VARCHAR(20) NOT NULL,
  SEXO			 VARCHAR(10),
  DT_NASCIMENTO  DATE,
  FOTO			 TEXT,
  DESCRICAO		 TEXT,
  STATUS_DW	     VARCHAR(10),
  TAMANHO_CAMISA VARCHAR(10),
  MD_AVALIACAO	 FLOAT
);

CREATE TABLE TB_ENDERECO(
  ID		     INTEGER PRIMARY KEY AUTO_INCREMENT,
  CEP			 VARCHAR(15),
  LOGRADOURO	 VARCHAR(50),
  NUMERO	     VARCHAR(10),
  BAIRRO	     VARCHAR(30),
  CIDADE		 VARCHAR(30),
  ESTADO	     VARCHAR(30),
  COMPLEMENTO	 VARCHAR(30)
);

CREATE TABLE TB_ENDERECO_PROP(
  ID_END         INTEGER,
  CPF_PROP		 VARCHAR(11),
  
  CONSTRAINT FK_CPF_PROP_ENDERECO FOREIGN KEY (CPF_PROP) REFERENCES TB_PROPRIETARIO (CPF),
  CONSTRAINT FK_ID_END_PROPRIETARIO FOREIGN KEY (ID_END) REFERENCES TB_ENDERECO (ID)
);

CREATE TABLE TB_ENDERECO_DW(
  ID_END		 INTEGER,
  CPF_DW		 VARCHAR(11),
  CONSTRAINT FK_CPF_DW_ENDERECO FOREIGN KEY (CPF_DW) REFERENCES TB_DOGWALKER (CPF),
  CONSTRAINT FK_ID_END_DOGWALKER FOREIGN KEY (ID_END) REFERENCES TB_ENDERECO (ID)
);

INSERT INTO tb_endereco(CEP,LOGRADOURO,NUMERO,BAIRRO,CIDADE,ESTADO,COMPLEMENTO) VALUES('14804103', 'Rua Dr Pedro Marao', '137', 'Vale do Sol', 'Araraquara', 'SP', null);
INSERT INTO tb_endereco(CEP,LOGRADOURO,NUMERO,BAIRRO,CIDADE,ESTADO,COMPLEMENTO) VALUES('14805440', 'Rua Jurandyr Goncalves Ferreira', '267','Maria Luiza', 'Araraquara', 'SP', null);

INSERT INTO TB_PROPRIETARIO VALUES('46677590895', 'gaquino1998@gmail.com', 'Dog-Friends2019', 'Gabriel Aquino', '+5516997901419', 'Masculino', '1998-10-20', NULL, 'Bacharelando em SI, Libriano e geek');
INSERT INTO TB_PROPRIETARIO VALUES('45031951826', 'isaaragon.01@gmail.com', 'Dog-Friends2019', 'Isabella Francischini', '+5516997344579', 'Feminino', '2001-05-17', NULL, 'Administradora Publica, UNESP, Gemeos');

INSERT INTO TB_ANIMAL(NOME,SEXO,DT_NASCIMENTO,FOTO,TIPO_ANIMAL,RACA,PORTE,FAZ_ATIVIDADE,COMPORTAMENTO,CPF_PROP) VALUES('Leona', 'Femea', '2016-03-10', NULL, 'Cachorro', 'Shih Tzu','Pequeno' ,'Não', 'Docil', '46677590895');
INSERT INTO TB_ANIMAL(NOME,SEXO,DT_NASCIMENTO,FOTO,TIPO_ANIMAL,RACA,PORTE,FAZ_ATIVIDADE,COMPORTAMENTO,CPF_PROP) VALUES('Aurora', 'Femea', '2016-03-10', NULL, 'Cachorro', 'Shih Tzu', 'Pequeno','Não', 'Docil', '46677590895');
INSERT INTO TB_ANIMAL(NOME,SEXO,DT_NASCIMENTO,FOTO,TIPO_ANIMAL,RACA,PORTE,FAZ_ATIVIDADE,COMPORTAMENTO,CPF_PROP) VALUES('Touluse', 'Macho', '2017-03-10', NULL, 'Cachorro', 'Shih Tzu','Pequeno' ,'Não', 'Docil', '45031951826');
INSERT INTO TB_ANIMAL(NOME,SEXO,DT_NASCIMENTO,FOTO,TIPO_ANIMAL,RACA,PORTE,FAZ_ATIVIDADE,COMPORTAMENTO,CPF_PROP) VALUES('Berlioz', 'Macho', '2018-03-10', NULL, 'Cachorro', 'Shih Tzu','Pequeno' ,'Não', 'Docil', '45031951826');
INSERT INTO TB_ANIMAL(NOME,SEXO,DT_NASCIMENTO,FOTO,TIPO_ANIMAL,RACA,PORTE,FAZ_ATIVIDADE,COMPORTAMENTO,CPF_PROP) VALUES('Belquior', 'Macho', '2019-07-21', NULL, 'Cachorro', 'Shih Tzu','Pequeno' ,'Não', 'Docil', '45031951826');

INSERT INTO TB_DOGWALKER VALUES(46677590895, 'gaquino1998@gmail.com', 'Dog-Friends2019', 'Gabriel Aquino', '+5516997901419', 'Masculino', '1998-10-20', NULL, 'Bacharelando em SI, Libriano e geek', 'Ativo', 'GG', 4.9);

INSERT INTO TB_ENDERECO_DW VALUES(1, 46677590895);

INSERT INTO TB_ENDERECO_PROP VALUES(1, 46677590895);
INSERT INTO TB_ENDERECO_PROP VALUES(2, 45031951826);